name: surf_flutter_test
description: Extensions and useful solutions for integration_test
version: 0.0.1
homepage: https://github.com/surfstudio/surf_flutter_test

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_gherkin: 
    git:
      url: https://github.com/jonsamwell/flutter_gherkin
      ref: integration_test__package_support
  flutter_test:
    sdk: flutter
  gherkin: 3.1.0
  integration_test:
    sdk: flutter
  path: ^1.8.1

dev_dependencies:
  surf_lint_rules: 1.5.0

flutter:
